name: Version branch & Cloudflare alias
on:
  release:
    types: [published]

permissions:
  contents: write   # lets the job push branches/tags

jobs:
  alias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # skip if the tag isn’t like v1.2.3
      - id: gate
        run: |
          [[ "${GITHUB_REF#refs/tags/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo "skip=yes" >>"$GITHUB_OUTPUT"

      - id: semver
        if: steps.gate.outputs.skip != 'yes'
        run: |
          echo "major=$(echo ${GITHUB_REF#refs/tags/v} | cut -d. -f1)" >>"$GITHUB_OUTPUT"

      # keep / move the vX branch at this commit
      - if: steps.gate.outputs.skip != 'yes'
        run: |
          git branch -f v${{steps.semver.outputs.major}} $GITHUB_SHA
          git push -f origin v${{steps.semver.outputs.major}}

      # one POST to attach vX.cook... to branch vX
      - if: steps.gate.outputs.skip != 'yes'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          PROJECT: cook
          MAJOR: ${{ steps.semver.outputs.major }}
        run: |
          ALIAS="v${MAJOR}.cook.luischav.es"
          curl -s -X POST \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: application/json" \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects/$PROJECT/domains" \
            --data "{\"name\":\"$ALIAS\",\"branch\":\"v$MAJOR\"}" \
          || true   # ignore “already exists”

